### ISSUE TITLE
Compiled DLL releases

### ISSUE THREAD

**Issue by bkraul** [EionRobb/pidgin-icon-override#17]
Where are the compiled Win32/64 DLL releases for this project? Some of us do not have the proper build environment to compile. Thanks.

**Comment by EionRobb** [comment]
Sorry about that, the dlls didn't get transferred over automatically when it was moved from Google code to github. I'll upload new dlls when I can

**Comment by EionRobb** [comment]
https://github.com/EionRobb/pidgin-icon-override/releases/tag/0.1
There ya go.  Sorry 'bout that

**Comment by bkraul** [comment]
Thank you!
